/*
 * This source file was generated by the Gradle 'init' task
 */
package org.astroEngine;

/**
 * A Simple library class
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
